"""Platform admin client onboarding wizard."""

from hiveflow.dna.web.admin.onboarding.guides import (
    load_connector_guide_markdown,
    render_connector_guide_html,
)
from hiveflow.dna.web.admin.onboarding.handlers import (
    build_status,
    client_deploy_status,
    connectors_ready_for_deploy,
    create_client_from_form,
    client_portal_site_urls,
    dna_stack_deployed,
    get_onboarding_client,
    initial_admin_from_config,
    invite_onboarding_admin,
    list_connector_companies,
    list_onboarding_clients,
    load_client_connector_credentials,
    load_connector_credentials,
    portal_deploy_ready,
    portal_dns_required,
    reporting_stack_deployed,
    save_client_from_form,
    save_connector_secret,
    trigger_deploy,
    validate_connector,
)
from hiveflow.dna.web.admin.onboarding.pipeline_handlers import (
    build_ingest_validation_report,
    client_pipeline_status,
    ingest_validation_report,
    trigger_dna_refresh,
    trigger_ingest_refresh,
)
from hiveflow.dna.web.admin.onboarding.views import (
    render_client_deploy,
    render_client_detail,
    render_client_pipelines,
    render_connector_credentials,
    render_onboarding_home,
    render_onboarding_wizard,
)

__all__ = [
    "build_ingest_validation_report",
    "build_status",
    "client_pipeline_status",
    "ingest_validation_report",
    "trigger_dna_refresh",
    "trigger_ingest_refresh",
    "client_deploy_status",
    "connectors_ready_for_deploy",
    "client_portal_site_urls",
    "create_client_from_form",
    "get_onboarding_client",
    "initial_admin_from_config",
    "invite_onboarding_admin",
    "list_connector_companies",
    "list_onboarding_clients",
    "load_client_connector_credentials",
    "load_connector_credentials",
    "dna_stack_deployed",
    "portal_deploy_ready",
    "portal_dns_required",
    "reporting_stack_deployed",
    "load_connector_guide_markdown",
    "render_client_deploy",
    "render_client_pipelines",
    "render_client_detail",
    "render_connector_credentials",
    "render_connector_guide_html",
    "render_onboarding_home",
    "render_onboarding_wizard",
    "save_client_from_form",
    "save_connector_secret",
    "trigger_deploy",
    "validate_connector",
]
